version: '3.7'

services:
    database:
        image: postgres:9.6.17-alpine
        restart: always
        env_file:
            - config.env
        volumes:
            - ./.postgres/live:/var/lib/postgresql/data
    lavalink:
        image: fredboat/lavalink:master-
        restart: always
        volumes:
            - ./application.yml:/opt/Lavalink/application.yml
    bot:
        image: topisenpai/kittybot:latest
        restart: always
        env_file:
            - config.env
        depends_on:
            - database
            - lavalink
