version: '3.7'

services:
    database:
        image: mysql:latest
        restart: always
        env_file:
            - config.env
        environment:
            - MYSQL_ROOT_HOST=%
        volumes:
            - /home/mysql/live:/var/lib/mysql
    bot:
        image: topisenpai/kittybot:latest
        restart: always
        env_file:
            - config.env
        depends_on:
            - database
    watchtower:
        image: containrrr/watchtower:latest
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        command: --interval 60
        depends_on:
            - bot
