version: '3.7'

services:
    bot:
        build: .
        restart: always
        env_file:
            - config.env
        depends_on:
            - database
    database:
        image: mysql:latest
        restart: always
        env_file:
            - config.env
        volumes:
            - ./.mysql/dev:/var/lib/mysql
