version: '3.7'

services:
    database:
        image: mysql:latest
        restart: on-failure
        env_file:
            - config.env
        environment:
            - MYSQL_ROOT_HOST=%
        volumes:
            - /home/mysql/1:/var/lib/mysql
    bot:
        image: topisenpai/kittybot:latest
        restart: on-failure
        env_file:
            - config.env
        depends_on:
            - database
    watchtower:
        image: containrrr/watchtower:latest
        restart: on-failure
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        command: --interval 5
        depends_on:
            - bot
