version: '3.7'

services:
    bot:
        build: .
        volumes: 
            - ./options.cfg:/home/kittybot/options.cfg
        restart: always
        depends_on:
            - database
    database:
        image: mysql:latest
        restart: always
        env_file:
            - config.env
#        environment:
#            MYSQL_ROOT_PASSWORD: 'YOU_ROOT_PASSWORD'
#            MYSQL_DATABASE: 'YOUR_DATA_BASE'
#            MYSQL_USER: 'YOUR_USER'
#            MYSQL_PASSWORD: 'YOUR_PASSWORD'
        volumes:
            - /home/mysql/data:/var/lib/mysql
    watchtower:
        image: containrrr/watchtower
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /home/docker/config.json:/config.json
        command: --interval 5
