version: '3.7'

services:
    database:
        image: mysql:latest
        restart: always
        env_file:
            - config.env
        volumes:
            - /home/mysql/staging:/var/lib/mysql
    bot:
        image: topisenpai/kittybot:staging
        restart: always
        env_file:
            - config.env
        depends_on:
            - database
