version: '3.7'

services:
    bot:
        build: .
        restart: always
        env_file:
            - config.env
        volumes:
            - ./options.cfg:/home/kittybot/options.cfg
        depends_on:
            - database
    database:
        image: mysql:latest
        restart: always
        env_file:
            - config.env
        volumes:
            - /home/mysql/dev:/var/lib/mysql
