version: '3.7'

services:
    bot:
        build: .
        volumes: 
            - ./options.cfg:/home/kittybot/options.cfg
        restart: always
        depends_on:
            - database
    database:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 'YOU_ROOT_PASSWORD'
            MYSQL_DATABASE: 'YOUR_DATA_BASE'
            MYSQL_USER: 'YOUR_USER'
            MYSQL_PASSWORD: 'YOUR_PASSWORD'
            MYSQL_ROOT_HOST: '%'
        volumes:
            - /home/mysql/data:/var/lib/mysql
